### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arpitBhalla**

### CODE REVIEW

**Comment by asbjornenge** [comment]
@arpitBhalla is `return (` not typically used for functional components? The example uses the `class` syntax.

**Comment by arpitBhalla** [comment]
@asbjornenge Render method of class component should also **return** JSx

**Comment by asbjornenge** [comment]
@arpitBhalla ah, I misread the code 😅 You are absolutely correct 👍

**Comment by arpitBhalla** [comment]
😊 thank you @asbjornenge , it's my first contribution 😅, yet small@

**Comment by asbjornenge** [comment]
@arpitBhalla very cool 😬 Thanks for your contribution 🙌🎉

**Pull request merged**
