### PR TITLE
React 15.2.0 compatibility.

### PR DESCRIPTION
**Pull request by lube**
Unknown HTML element attributes now trigger warnings. See Hacker0x01/react-datepicker#517 (comment)

### CODE REVIEW

**Comment by asbjornenge** [comment]
@educastellano could you take a look at this one? LGTM, but you use this module more than I do, so perhaps you have some insight? Feel free to merge if you see fit :smile:  Let me know if you need help publishing to `npm`.

@Lube sorry for the super late reply, I somehow missed this one.

**Comment by n1k0** [comment]
Please someone land this and publish a new release. Pretty. Please.

**Comment by n1k0** [comment]
Thanks for your reactivity :+1:

**Comment by educastellano** [comment]
I fixed a "es6 destructuring" that I think it was not correct... It's now merged and published :)

**Pull request merged**
